# Generated by Django 6.0.6 on 2026-07-07 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_delete_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название акции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Скидка, %')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applies_to_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.category', verbose_name='Категория')),
            ],
        ),
    ]
