# Generated by Django 6.0.6 on 2026-07-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Акция', 'verbose_name_plural': 'Акции'},
        ),
    ]
