# Generated by Django 6.0.6 on 2026-07-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_alter_promotion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(help_text='Введите число от 1 до 100 (например, 15 для скидки 15%)', verbose_name='Скидка, %'),
        ),
    ]
