# Generated by Django 6.0.6 on 2026-06-14 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last_digits',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='brand',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип карты'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_last_four',
            field=models.CharField(default=0, max_length=4, verbose_name='Последние 4 цифры'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Месяц'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Год'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
    ]
