# Generated by Django 6.0.6 on 2026-07-23 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_favorite_options_alter_profile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_mask',
            field=models.CharField(blank=True, help_text='Отображаемая маска карты, без полных данных', max_length=32, null=True, verbose_name='Маска карты'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Тип способа оплаты'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='yookassa_payment_method_id',
            field=models.CharField(blank=True, help_text='Токен/ID способа оплаты, возвращаемый YooKassa', max_length=64, null=True, verbose_name='ID способа оплаты в YooKassa'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user', 'is_default'), name='unique_default_payment_method_per_user'),
        ),
    ]
