# Generated by Django 6.0.6 on 2026-07-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_fix_original_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Полная стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'В обработке'), ('confirmed', 'Подтверждён'), ('shipped', 'Отправлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
