# Generated by Django 6.0.6 on 2026-07-02 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_original_total_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'В обработке'), ('confirmed', 'Подтверждён'), ('shipped', 'Отправлен'), ('completed', 'Завершён'), ('cancelled', 'Отменён'), ('paid', 'Оплачен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ'),
        ),
    ]
