# Generated by Django 6.0.6 on 2026-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('card', 'Банковская карта'), ('cash', 'При получении')], default='cash', max_length=20, null=True, verbose_name='Способ оплаты'),
        ),
    ]
