# Generated by Django 6.0.6 on 2026-07-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_type_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена со скидкой (на момент покупки)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная цена (без скидок)'),
        ),
    ]
