"""
Django settings for techstore project.
Generated by 'django-admin startproject' using Django 6.0.1.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# -----------------------------------------------------------------------------
# 1. Настройка BASE_DIR и загрузка .env (ТОЛЬКО ОДИН РАЗ В САМОМ НАЧАЛЕ)
# -----------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv_path = BASE_DIR / '.env'

if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)

# -----------------------------------------------------------------------------
# 2. Основные настройки безопасности
# -----------------------------------------------------------------------------
SECRET_KEY = 'django-insecure-zR_w7OKH2AufodOZJl_MN10hrDaC0Gk9P_wSCfSHpZZ3SX6wwobO17tZ5TdWHtEp5SE'
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']

# -----------------------------------------------------------------------------
# 3. Приложения и middleware
# -----------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    #'django.contrib.auth',
    'techstore.apps.CustomAuthConfig',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Твои приложения
    'accounts.apps.AccountsConfig',
    'products',
    'cart',
    'promotions',
    'orders',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techstore.urls'
WSGI_APPLICATION = 'techstore.wsgi.application'

# -----------------------------------------------------------------------------
# 4. База данных
# -----------------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------------------------------------------------------
# 5. YooKassa (Настройки платёжной системы)
# -----------------------------------------------------------------------------
YOOKASSA_ACCOUNT_ID = os.getenv('YOOKASSA_ACCOUNT_ID')
YOOKASSA_SECRET_KEY = os.getenv('YOOKASSA_SECRET_KEY')
BASE_URL = os.getenv('BASE_URL', 'http://127.0.0.1:8000')

if not YOOKASSA_ACCOUNT_ID or not YOOKASSA_SECRET_KEY:
    raise ImproperlyConfigured("Не заданы переменные YOOKASSA_ACCOUNT_ID или YOOKASSA_SECRET_KEY в .env")

# -----------------------------------------------------------------------------
# 6. Шаблоны и контекстные процессоры
# -----------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.categories_processor',
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# 7. Статика и Медиа 
# -----------------------------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------------------------------------------------------
# 8. Валидация паролей
# -----------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 12}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
    {'NAME': 'accounts.validators.ComplexityValidator', 'OPTIONS': {'min_uppercase': 1, 'min_lowercase': 1, 'min_digits': 2, 'min_special': 1}},
]

# -----------------------------------------------------------------------------
# 9. Интернационализация и время
# -----------------------------------------------------------------------------
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'
MODELTRANSLATION_TRANSLATION_REGISTRY = 'techstore.translation'

LANGUAGES = [
    ('ru', 'Russian'),
    ('en', 'English'),
]

TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# -----------------------------------------------------------------------------
# 10. Кэш и прочие настройки
# -----------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

CART_SESSION_ID = 'cart'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# -----------------------------------------------------------------------------
# 11. Логирование 
# -----------------------------------------------------------------------------
LOGS_DIR = BASE_DIR / 'logs'
# ВАЖНО: Не вызывай LOGS_DIR.mkdir() здесь! 
# FileHandler сам создаст файл, но если папки нет, он может упасть.
# Лучший способ — создать папку один раз вручную или через скрипт миграции/запуска.
# Для быстрой проверки можешь раскомментировать строку ниже, но помни, что она выполнится при каждом импорте:
# LOGS_DIR.mkdir(exist_ok=True) 

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            # Используем str() для совместимости, хотя Path тоже работает в новых версиях
            'filename': str(LOGS_DIR / 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'orders': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

