# Generated by Django 6.0.6 on 2026-07-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_promotion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
