# Generated by Django 6.0.6 on 2026-07-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
