# Generated by Django 6.0.3 on 2026-04-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, help_text="Укажите характеристики в формате 'Параметр: значение' через новую строку", verbose_name='Характеристики продукта'),
        ),
    ]
