# Generated by Django 6.0.3 on 2026-04-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
