# Generated by Django 6.0.3 on 2026-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_is_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristics',
            new_name='specifications',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
